# Generated by Django 3.2.5 on 2023-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
